# Generated by Django 3.1 on 2021-11-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=60)),
                ('department_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=60)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=60)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department')),
            ],
        ),
    ]
